---
max_opts: 100000000
eval_episodes: 1
eval_threshold: ~
model_dir: "./border/examples/model/dqn_asterix_ddqn_per"
opt_interval: 1
eval_interval: 500000
record_interval: 50000
save_interval: 10000000
