[package]
name = "border-py-gym-env"
version = "0.0.5"
authors = ["Taku Yoshioka <yoshioka@laboro.ai>"]
edition = "2018"
rust = "1.65.0"

description = "Reinforcement learning library"
repository = "https://github.com/taku-y/border"
keywords = ["rl"]
categories = ["science"]
license = "MIT OR Apache-2.0"
readme = "README.md"
autoexamples = false

[dependencies]
border-core = { version = "0.0.5", path = "../border-core" }
numpy = "0.14.1"
pyo3 = { version = "=0.14.5", default-features = false, features = ["auto-initialize"] }
serde = { version = "=1.0.126", features = ["derive"] }
log = "0.4"
num-traits = "0.2.14"
ndarray = { version = "0.15", features = ["serde"] }
anyhow = "1.0.38"
tch = { version = "0.8.0", optional = true }
image = "0.23.14"

[dev-dependencies]
fastrand = "1.4.0"
env_logger = "0.8.2"
csv = "1.1.5"

[features]
default = ["tch"]

[[example]]
name = "random_cartpole"
test = true

[[example]]
name = "random_lunarlander_cont"
test = true

[[example]]
name = "random_ant"
test = false # Skip test for now, PyBullet Gym requires modify code (see Dockerfile in this repository)

[[example]]
name = "pybullet_pyo3"
